title: Just For Fun
author: Urvi Mitra
email: hahahahahah@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
 created this to learn how to use github pages 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
